runtime: python39
service: frontend-service

handlers:
- url: /favicon.ico
  static_files: build/favicon.ico
  upload: build/favicon.ico
- url: /static/(.*)
  static_files: build/static/\1
  upload: build/static/(.*)
- url: /assets/(.*)
  static_files: build/assets/\1
  upload: build/assets/(.*)
- url: /(.*)
  static_files: build/\1
  upload: build/(.*)

# Serve index.html for root (fallback)
- url: /
  static_files: build/index.html
  upload: build/index.html
